[tool.poetry]
name = "loracap"
version = "0.1.0"
description = ""
authors = ["Spencer <love4yzp@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pyserial = "^3.5"
crc = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"